### ISSUE TITLE
Side Bar scroll bar/White space

### ISSUE THREAD

**Issue by daniherr** [polyswarm/documentation#153]
The navigation box on the left side of pages seams to have a bug when it extends past the screen. It creates a scroll bar.
![scrollbar](https://user-images.githubusercontent.com/35880494/51354992-ced26680-1a72-11e9-8640-7d679be735bf.JPG)

There also seams to be a lot of white space surrounding it. It takes up about 1/3 of my screen. 
![whitespace](https://user-images.githubusercontent.com/35880494/51355021-e4e02700-1a72-11e9-876e-d48af370a4bb.JPG)

both issues appear on my 24inch 1080p desktop monitor and my 4k 14inch laptop

**Comment by mrtizmoatwork-psadmin** [comment]
resolved
