### ISSUE TITLE
Clarification on EICAR Detection Logic

### ISSUE THREAD

**Issue by daniherr** [polyswarm/documentation#154]
In the Level 0 page (https://docs.polyswarm.io/microengines-scratch-to-eicar/) under "Implement an EICAR Scanner & Microengine"

It tells you to open the __init__.py file, but it doesnt explain that you should copy and paste the code below under Write EICAR Detection Logic to continue. 

Right now the wording is just "Try your hand at writing a scan function that detects the EICAR test file. If you’d like some inspiration, below are a couple of ways to go about it."

I think it would be clearer on what you should do if it says, "Copy and replace the code below to __init__.py, or write your own scan function that detects the EICAR test file."

**Comment by mrtizmoatwork** [comment]
@daniherr commented on the PR that she was good with the change.

**Comment by mrtizmoatwork-psadmin** [comment]
resolved
