### ISSUE TITLE
Docs navigation

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/documentation#81]
Went to docs.polyswarm.io looking for tutorials, was unclear to me what "next steps" there are after the background info landing page. Eventually found it in the nav up top under "Getting Started". Think this is unintuitive and also not a great header for microengine developement tutorials. Perhaps a link at the bottom of the page would be an improvement.

**Comment by daniherr** [comment]
Something I noticed in docs.polyswarm.io, shouldn't logo redirect to polyswarm.io?

**Comment by mrjoshc** [comment]
Text is now aligned with next article button. As far as the redirect, the thought there is that takes you to the docs homepage. The footer logo takes you to polyswarm.io.

**Comment by mrjoshc** [comment]
@mjkoo @daniherr If that all looks good, we can close this out.
